<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rimlight.Core/Rimlight.Core.csproj" />
    <ProjectReference Include="../Rimlight.Platform/Rimlight.Platform.csproj" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.3.2" />
  </ItemGroup>
</Project>
